module.exports = {
    messages: [
        "cc",
        "cl",
        "dm",
        "ditme",
        "địt mẹ mày",
        "cút",
        "biến",
        "cái lồn",
        "con kẹt",
        "con cặc",
        "cai lon me may",
        "con me may",
        "condi",
        "buồi",
        "dái",
        "địt",
        "lồn",
        "cặc",
    ],
};
